# This script will import the h5 files from our sleap inference pipeline output. These files were generated by first running inference on the video using sleap, making a .slp file. 
# This .slp file was exported with sleapio into a CSV file. That CSV file was converted to H5 using pandas to save space.
# After reading these H5 files we will assign identity based on the X/Y coordinates each aphid is confined to (i.e. ROI json data).
# Finally we will export these ID assigned abdomen coordinates to a single parquet file for each hour.

# In a secondary script we will combine these 96 parquet files into a single parquet file for each video/experimental replicate.

import argparse
import json
import re
from pathlib import Path
import pandas as pd
import numpy as np

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--h5_in", required=True)
    parser.add_argument("--json_in", required=True)
    parser.add_argument("--parquet_out", required=True)
    args = parser.parse_args()

    # 1. Load Boxes
    with open(args.json_in, 'r') as f:
        boxes = json.load(f)['boxes']

    # 2. Load Data & Isolate Abdomens (Your exact prototype logic here)
    df = pd.read_hdf(args.h5_in, key='sleap_data')
    ab_cols = ['frame_idx'] + [col for col in df.columns if '.ab.x' in col or '.ab.y' in col]
    df_ab = df[ab_cols].copy()

    # Dynamic instance detection
    instances = set([col.split('.')[0] for col in df_ab.columns if col.startswith('inst')])
    
    long_data = []
    for inst in instances:
        x_col, y_col = f'{inst}.ab.x', f'{inst}.ab.y'
        if x_col in df_ab.columns and y_col in df_ab.columns:
            temp = df_ab[['frame_idx', x_col, y_col]].copy()
            temp.columns = ['frame_idx', 'x', 'y']
            temp = temp.dropna(subset=['x', 'y'])
            long_data.append(temp)
            
    if not long_data:
        # Failsafe if video is completely empty
        df_long = pd.DataFrame(columns=['frame_idx', 'x', 'y', 'individual', 'video_id', 'treatment', 'replicate'])
    else:
        df_long = pd.concat(long_data, ignore_index=True)
        
        # Spatial Assignment
        def assign_chamber(x, y, boxes):
            if pd.isna(x) or pd.isna(y): return np.nan
            for box in boxes:
                if (box['x_min'] <= x <= box['x_max']) and (box['y_min'] <= y <= box['y_max']):
                    return box['label'] 
            return np.nan 
            
        df_long['individual'] = df_long.apply(lambda row: assign_chamber(row['x'], row['y'], boxes), axis=1)
        df_long = df_long.dropna(subset=['individual'])
        df_long['individual'] = df_long['individual'].astype(int)
        
        # Metadata Injection
        filename = Path(args.h5_in).stem
        df_long['video_id'] = str(filename)
        df_long['treatment'] = 'LD-diet' if 'LD' in filename.upper() else 'DD-diet' if 'DD' in filename.upper() else 'Unknown'
        
        rep_match = re.search(r'(rep\d+)', filename, re.IGNORECASE)
        df_long['replicate'] = str(rep_match.group(1).lower() if rep_match else 'unknown')

    # 3. Export Intermediate
    df_long.to_parquet(args.parquet_out, engine='pyarrow', compression='snappy', index=False)

if __name__ == "__main__":
    main()