# h5_spatial_assign.py
# This script will import the h5 files from our sleap inference pipeline output. These files were generated by first running inference on the video using sleap, making a .slp file. 
# This .slp file was exported with sleapio into a CSV file. That CSV file was converted to H5 using pandas to save space.
# After reading these H5 files we will assign identity based on the X/Y coordinates each aphid is confined to (i.e. ROI json data).
# update: we also grab prediction score, add global frame count, and calculate ZT time based on the timestamp in the filename. (ZT0 = 8am)
# Finally we will export these ID assigned abdomen coordinates to a single parquet file for each hour.

# In a secondary script we will combine these 96 parquet files into a single parquet file for each video/experimental replicate.

import argparse
import json
import re
from pathlib import Path
import pandas as pd
import numpy as np

def get_frame_offset(video_id_string):
    """Extracts the start frame from the filename to build a continuous global timeline."""
    match = re.search(r'_(\d+)-\d+(?:_sleap)?$', video_id_string)
    if match:
        return int(match.group(1))
    return 0

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--h5_in", required=True)
    parser.add_argument("--json_in", required=True)
    parser.add_argument("--parquet_out", required=True)
    args = parser.parse_args()

    # 1. Load Boxes
    with open(args.json_in, 'r') as f:
        boxes = json.load(f)['boxes']

    # 2. Load Data & Isolate Abdomens
    df = pd.read_hdf(args.h5_in, key='sleap_data')
    ab_cols = ['frame_idx'] + [col for col in df.columns if '.ab.x' in col or '.ab.y' in col or '.ab.score' in col]
    df_ab = df[ab_cols].copy()

    # Dynamic instance detection
    instances = set([col.split('.')[0] for col in df_ab.columns if col.startswith('inst')])
    
    long_data = []
    for inst in instances:
        x_col, y_col, score_col = f'{inst}.ab.x', f'{inst}.ab.y', f'{inst}.ab.score'
        if x_col in df_ab.columns and y_col in df_ab.columns:
            cols = ['frame_idx', x_col, y_col]
            has_score = score_col in df_ab.columns
            if has_score:
                cols.append(score_col)
                
            temp = df_ab[cols].copy()
            temp.columns = ['frame_idx', 'x', 'y', 'score'] if has_score else ['frame_idx', 'x', 'y']
            temp = temp.dropna(subset=['x', 'y'])
            long_data.append(temp)
            
    if not long_data:
        # Failsafe if video is completely empty
        df_long = pd.DataFrame(columns=[
            'x', 'y', 'score', 'individual', 'video_id', 
            'treatment', 'replicate', 'global_frame'
        ])
    else:
        df_long = pd.concat(long_data, ignore_index=True)
        
        # Spatial Assignment
        def assign_chamber(x, y, boxes):
            if pd.isna(x) or pd.isna(y): return np.nan
            for box in boxes:
                if (box['x_min'] <= x <= box['x_max']) and (box['y_min'] <= y <= box['y_max']):
                    return box['label'] 
            return np.nan 
            
        df_long['individual'] = df_long.apply(lambda row: assign_chamber(row['x'], row['y'], boxes), axis=1)
        df_long = df_long.dropna(subset=['individual'])
        
        # Metadata Injection
        filename = Path(args.h5_in).stem
        df_long['video_id'] = str(filename)
        df_long['treatment'] = 'LD-diet' if 'LD' in filename.upper() else 'DD-diet' if 'DD' in filename.upper() else 'Unknown'
        
        rep_match = re.search(r'(rep\d+)', filename, re.IGNORECASE)
        df_long['replicate'] = str(rep_match.group(1).lower() if rep_match else 'unknown')

        # --- TIME INJECTION ---
        offset = get_frame_offset(filename)
        df_long['global_frame'] = df_long['frame_idx'] + offset

        # Sort directly by continuous timeline
        df_long = df_long.sort_values(by=['individual', 'global_frame']).reset_index(drop=True)

        
        # Update to trim fat and remove some redundant and data heavy columns we probably dont need
        
        
        # 1. Coordinates: Cast straight to 16-bit integers (4x smaller than float64)
        df_long['x'] = df_long['x'].astype(np.int16)
        df_long['y'] = df_long['y'].astype(np.int16)
        
        # 2. Score: Round to 2 decimals (e.g., 0.89) then downcast to 32-bit. 
        # TODO: score seems to not be getting rounded properly, still showing high precision in parquet file. Sizes are OK though.
        if 'score' in df_long.columns:
            df_long['score'] = df_long['score'].round(2).astype(np.float32)

        # 3. Global Frame & ID: Downcast to smallest safe integers
        df_long['global_frame'] = df_long['global_frame'].astype(np.int32)
        df_long['individual'] = df_long['individual'].astype(np.int16)

        # 4. Strings: Convert redundant text to 'category' type
        df_long['video_id'] = df_long['video_id'].astype('category')
        df_long['treatment'] = df_long['treatment'].astype('category')
        df_long['replicate'] = df_long['replicate'].astype('category')

        # 5. DROP redundant internal tracking column
        df_long = df_long.drop(columns=['frame_idx'])

    # 3. Export Intermediate
    df_long.to_parquet(args.parquet_out, engine='pyarrow', compression='snappy', index=False)

if __name__ == "__main__":
    main()