# config.yaml
paths:
  # paths to the h5 files. kept in aim 2 dir on OneDrive. Also backed up on D: drive on lab server.
  # providing absolute path for simplicity, as our data is backed up on OneDrive but we don't want to run this pipeline on OneDrive...
  h5_root: "D:/RpadiSleapInferencePipeline_Output"

  # paths to the ROI json files. These are in the ROItools repo, which is a sibling to the H5toDatabase repo. Providing absolute path as we wont be running this pipeline on OneDrive...
  # if running in the Rpadi_Video_Tracking_Analysis repo, the relative path would be:
  #roi_root: "../ROItools"
  # but since we are running this on the lab server, we will use the absolute path to the ROItools repo on the lab server:
  roi_root: "C:/Users/nalamlab/OneDrive - Colostate/NIFA_PROJECT/Obj2/Rpadi_Video_Tracking_Analysis/ROItools"

  # output dir will remain in the current working dir where the snakefile is executed (H5toDatabase)
  output_dir: "output"

# Explicitly map the replicate folder to its Treatment and ROI file. Rep folders are nested in `LD-Diet` or `DD-Diet` folders.
replicates:
  # LD rep 1
  "agesync_7-29-25-rep1":
    treatment: "LD-Diet"
    json_file: "LD-diet_agesync_7-29-25-rep1_Camera0_20250804_122315_0-215999.json"
  
  # LD rep 2
  "agesync_8-8-25-rep2":
    treatment: "LD-Diet"
    json_file: "LD-diet_agesync_8-8-25-rep2_Camera0_20250814_125919_0-215999.json"

  # LD rep 3
  "agesync_8-19-25-rep3":
    treatment: "LD-Diet"
    json_file: "LD-diet_agesync_8-19-25-rep3_Camera0_20250825_131731_0-215999.json"
  
  # LD rep 4
  "agesync_8-25-25-rep4":
    treatment: "LD-Diet"
    json_file: "LD-diet_agesync_8-25-25-rep4_Camera0_20250901_123631_0-215999.json"

  # LD rep 5
  "agesync_9-11-25-rep5":
    treatment: "LD-Diet"
    json_file: "LD-diet_agesync_9-11-25-rep5_Camera0_20250918_122403_0-215999.json"

  # LD rep 6
  "agesync_9-18-25-rep6":
    treatment: "LD-Diet"
    json_file: "LD-diet_agesync_9-18-25-rep6_Camera0_20250924_124210_0-215999.json"    

  # LD rep 7
  "agesync_1-2-26-rep7":
    treatment: "LD-Diet"
    json_file: "LD-diet_agesync_1-2-26-rep7_Camera0_20260109_125141_0-215999.json"

  # LD rep 8
  "agesync_1-23-26-rep8":
    treatment: "LD-Diet"
    json_file: "LD-diet_agesync_1-23-26-rep8_Camera0_20260130_134713_0-215999.json"

  ## DD reps

  # DD rep 1
  "agesync_10-3-25-rep1-DD":
    treatment: "DD-Diet"
    json_file: "DD-diet_agesync_10-3-25-rep1_Camera0_20251009_125400_0-215999.json"

  # DD rep 2
  "agesync_10-23-25-rep2-DD":
    treatment: "DD-Diet"
    json_file: "DD_diet_agesync_10-23-25-rep2_Camera0_20251029_125846_0-215999.json"

  # DD rep 3
  "agesync_11-17-25-rep3-DD":
    treatment: "DD-Diet"
    json_file: "DD-diet_agesync_11-17-25-rep3_Camera0_20251123_124946_0-215999.json"

  # DD rep 4
  "agesync_11-28-25-rep4-DD":
    treatment: "DD-Diet"
    json_file: "DD-diet_agesync_11-28-25-rep4_Camera0_20251204_132157_0-215999.json"

  # DD rep 5
  "agesync_12-16-25-rep5-DD":
    treatment: "DD-Diet"
    json_file: "DD-diet_agesync_12-16-25-rep5_Camera0_20251223_133950_0-215999.json"

  # DD rep 6
  "agesync_12-26-25-rep6-DD":
    treatment: "DD-Diet"
    json_file: "DD-diet_agesync_12-26-25-rep6_Camera0_20260102_134408_0-215999.json"  

  # DD rep 7
  "agesync_2-11-26-rep7-DD":
    treatment: "DD-Diet"
    json_file: "DD-diet_agesync_2-11-26-rep7_Camera0_20260218_131644_0-215999.json"

  # DD rep 8
  "agesync_2-18-26-rep8-DD":
    treatment: "DD-Diet"
    json_file: "DD-diet_agesync_2-18-26-rep8_Camera0_20260225_133112_0-215999.json"